### PR TITLE
Document camera spline node smoothing

### PR DESCRIPTION
**Pull request by Lucas7yoshi**
Documented camera smoothing styles by pulling rendered cam coordinates throughout interpolation and graphing

### CODE REVIEW

**Comment by Lucas7yoshi** [comment]
> This will require verification, but if my partial-documentation is correct there are twenty-something 'smoothing styles' (easing functions), with only the first four being used in the script natives. See, `0x1402AA9D4` -> `0x1402689B0` (1604).
> 
> 1/2/3 look like easeInSine/easeOutSine/easeInOutSine (seems corroborated by your plots). While 23/24/25 look like easeInCirc/easeOutCirc/easeInOutCirc.

I can try plotting over 3 and see how it looks when I get home. I was intended to but got side tracked. 

I'll find a way to dump them more conveniently by just looping through every single one

**Comment by Lucas7yoshi** [comment]
documented everything
should be good now

**Comment by Lucas7yoshi** [comment]
resolved conflict

**Comment by stannum-cfx** [comment]
Great documentation/data, thanks.

**Pull request merged**
