### PR TITLE
Update GetOffsetFromEntityInWorldCoords.md

### PR DESCRIPTION
**Pull request by draobrehtom**
This is an example implementation of `GetOffsetFromEntityInWorldCoords` which can be used on server-side.

### CODE REVIEW

**Comment by gottfriedleibniz** [comment]
Using Lua5.4 you can:

```lua
local glm = require('glm')
function GetOffsetFromEntityInWorldCoords(entity, offX, offY, offZ)
	local pos = GetEntityCoords(entity)
	local rot = GetEntityRotation(entity) -- ZXY
	local rx, ry, rz = math.rad(rot.x), math.rad(rot.y), math.rad(rot.z)

	-- This function would require emulation for Lua 5.3, should be quite easy to find
	local q = glm.quatEulerAngleZXY(rz, rx, ry) 

	return pos + q * vec3(offX, offY, offZ)
end
```

**Comment by draobrehtom** [comment]
> Also, I'm not entirely sure how to feel about the natives repository containing fairly long/complex examples. Snippets and other utility functions should probably exist elsewhere.

I agree, but where? When I was looking for this native on server side first of all I was searching it in natives docs.

**Comment by draobrehtom** [comment]
And by making such pull request I have a hope that such server native will appear on server side.

**Comment by draobrehtom** [comment]
Well, actually maybe this place will be better: https://forum.cfx.re/c/general-discussion/feature-requests/

**Pull request closed without merging**
