### PR TITLE
Maximum float

### PR DESCRIPTION
**Pull request by Yadiiiig**
Used multiple floats that are higher then 1.0. Amount of vehicles keeps being the same.

### CODE REVIEW

**Comment by gottfriedleibniz** [comment]
From the looks of it, SetSomeVehicleDensityMultiplierThisFrame simply chains together SetRandomVehicleDensityMultiplierThisFrame and SetParkedVehicleDensityMultiplierThisFrame.

```c
void __fastcall SetVehicleDensityMultiplierThisFrame(float a1)
{
  if ( *(float *)&randomVehicleDensity >= a1 )
    randomVehicleDensity = LODWORD(a1);
  if ( *(float *)&parkedVehicleDensity >= a1 )
    parkedVehicleDensity = LODWORD(a1);
}
```

Also, _SetSomeVehicleDensityMultiplierThisFrame is the only vehicle density native that allows values greater than 1.0.

**Comment by blattersturm** [comment]
> SetSomeVehicleDensityMultiplierThisFrame

SET_AMBIENT_VEHICLE_RANGE_MULTIPLIER_THIS_FRAME?

**Comment by FumaPraQue** [comment]
I can confirm SetSomeVehicleDensityMultiplierThisFrame really set Ambient Vehicle Range, i use that native for a long time, you can see better if you set the range in 0.1. The ambient cars will spawn too close of you.

**Comment by gottfriedleibniz** [comment]
Confirmation confirmed.

**Comment by stannum-cfx** [comment]
> > SetSomeVehicleDensityMultiplierThisFrame
> 
> SET_AMBIENT_VEHICLE_RANGE_MULTIPLIER_THIS_FRAME?

Implemented in: https://github.com/citizenfx/natives/commit/4378acd7014de66fe559a2ce8cfb42fcb2b8b4af

**Pull request merged**
