### PR TITLE
Cleanup Pass 1

### PR DESCRIPTION
**Pull request by LWSS**
manual pass mainly focused on param types

basic test done with native-doc-tooling

### CODE REVIEW

**Comment by AvarianKnight** [comment]
How is this going to end up working for over all compatibility?

**Comment by LWSS** [comment]
> How is this going to end up working for over all compatibility?

the older game versions are going to be removed eventually

**Comment by AvarianKnight** [comment]
> > How is this going to end up working for over all compatibility?
> 
> the older game versions are going to be removed eventually

But that doesn't solve the problem that changing the ABI will cause mono v1 to break

**Comment by LWSS** [comment]
> > > How is this going to end up working for over all compatibility?
> > 
> > 
> > the older game versions are going to be removed eventually
> 
> But that doesn't solve the problem that changing the ABI will cause mono v1 to break

Thanks for pointing that out

Yeah this will have to wait until v2, or if we lock v1's natives state

**Comment by AvarianKnight** [comment]
Both

**Comment by ahcenezdh** [comment]
So why not using cs_type?

**Comment by AvarianKnight** [comment]
Because a lot of natives are old and have gotten new arguments over time. Adding new arguments would break ABI compatibility with existing C# resources causing them to fail to run. 

This is fixed with mono_v2, but it looks like its going to be a long time until mono_v2 is ready

**Pull request closed without merging**
