### PR TITLE
Better way to make people use FiveM docs

### PR DESCRIPTION
**Pull request by FreakOutModz**
Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

### CODE REVIEW

**Comment by FreakOutModz** [comment]
@gottfriedleibniz I understand why you are doing the PR, but it automatically removes the work done by the user for the native improvisation

**Comment by AvarianKnight** [comment]
You left the link in code brackets, which according to the contribution guidelines is only meant for things that were imported from the NativeDB you can see that here [here](https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md#descriptions). It's much easier to go through and fix it themselves as a lot of the time when you request any changes the contributor to do so, they will take a very long time, or they won't do it at all, as can be seen [here](https://github.com/citizenfx/natives/pull/524).

**Comment by FreakOutModz** [comment]
Totally agree, I had not seen on this point. Thank you for the clarification. Also I thought I had to put the link between brackets, thank you for the info!

**Comment by gottfriedleibniz** [comment]
While poor git etiquette, it is much easier to squash everything, test, then apply the necessary fixes. Many of these PRs have been ignored for months now anyway.

**Pull request closed without merging**
