### PR TITLE
chore(natives): standardize threading with Citizen

### PR DESCRIPTION
**Pull request by ahcenezdh**
Standardized threading and waiting functions for consistency across the documentation.

### CODE REVIEW

**Comment by AvarianKnight** [comment]
Would it not be better to prefer the short forms over ones with Citizen prefix?

**Comment by ahcenezdh** [comment]
> Would it not be better to prefer the short forms over ones with Citizen prefix?

Good question! Honestly, I did it with Citizen, since in most examples, there is Citizen, and a lot of people are using it.

**Comment by PsychoShock** [comment]
Hello,

There's no point of doing this since it's all the same. You can check https://github.com/citizenfx/fivem/blob/master/data/shared/citizen/scripting/lua/scheduler.lua#L136. Also, it will be most common to remove it that adding it back. Only reason, some has `Citizen` is from old PR's.

Thanks.

**Comment by ahcenezdh** [comment]
Hello, I'm aware of that. The objective, as indicated by the title of this PR, is to standardize the use of "Citizen" (though it could also be without "Citizen") for greater consistency. This approach aims to prevent new scripters on FiveM from getting lost. It would be better for the documentation if we choose to stick with only one of the two options either with "Citizen" or without.

**Pull request closed without merging**
