### PR TITLE
Create GetVehiclePedIsIn.md

### PR DESCRIPTION
**Pull request by Quattro20v**

### CODE REVIEW

**Comment by sgottelk** [comment]
Duplicate of https://github.com/citizenfx/natives/blob/master/PED/GetVehiclePedIsIn.md ?

**Comment by sgottelk** [comment]
Nah, it should be mvoed here: https://github.com/citizenfx/fivem/tree/master/ext/native-decls

**Comment by sgottelk** [comment]
~~Duplicate of https://github.com/citizenfx/natives/blob/master/PED/GetVehiclePedIsIn.md?~~
 
~~Nah, it should be moved here: https://github.com/citizenfx/fivem/tree/master/ext/native-decls~~

It's already here https://github.com/citizenfx/fivem/blob/2570cce559e1b48ddbc4d76de2ba3a55771ba13f/ext/native-decls/GetVehiclePedIsIn.md

**Comment by stannum-cfx** [comment]
CFX natives are no longer in this repository.

**Pull request closed without merging**
