### PR TITLE
Restore dead Imgur links

### PR DESCRIPTION
**Pull request by ItsJunction**
Many Imgur images were deleted at some point within the last year, this PR restores a fair few of them. Please let me know if I'm missing any not listed below.

Note this PR does NOT restore any dead links found in "unmodern" docs.

 The following links I could not find anything for:
- https://i.imgur.com/qLbXWcQ.png in AddBlipForArea.md
- https://i.imgur.com/0j7O7Rh.png in AddBlipForArea.md
- https://i.imgur.com/hS6ki7p.png in SetRadiusBlipEdge.md

### CODE REVIEW

**Comment by AvarianKnight** [comment]
With imgur starting to block/delete more images it might be worth putting these images on the forums and use the image link from the forums

**Comment by PsychoShock** [comment]
Hello,

I've noticed that uploading images directly from users might not be the most efficient way to handle visuals. Like Avarian said, with Imgur blocking images on CFX wouldn't be a good idea. To streamline the process and ensure clarity in the documentation, implementing a new section specifically for game documents might be a good idea. From now on, all images related to game documentation could be uploaded to the designated section directly.

To facilitate this transition, you can update the `contribution.md` file. Contributors would be encouraged to refer to this file for guidelines on uploading images. By consolidating all visual elements in one place, it will be easier for anyone to replace / update them.

Thanks

**Comment by ook3D** [comment]
some additional options for image hosting could be an official CFX one, or use other options such as https://imgbb.com/ :)

**Comment by 4mmonium** [comment]
While I cannot really comment on this right now, I think hosting the images on external sources won't stop these issues from happening and will cause more PRs to be opened where new links are provided to resolve '404' URLs.

Ideally, hosting this somewhere internally might be a better idea, but it's not something I can comment on at the moment. Will provide feedback once I have it 🙂

**Comment by AvarianKnight** [comment]
> Ideally, hosting this somewhere internally might be a better idea, but it's not something I can comment on at the moment. Will provide feedback once I have it 🙂

It would be possible to just have an unlisted thread on the forums used for image uploads on native docs

**Comment by VIRUXE** [comment]
@PsychoShock pointed me to this PR, which solves the issue I created, for the most part at least.

I'll pick up on this on another PR but with images uploaded from GitHub's web interface, where images get uploaded to their cdn.

For reference: https://github.com/citizenfx/fivem-docs/issues/425

**Comment by AvarianKnight** [comment]
This isn't a valid solution, as has been previously said.

**Pull request closed without merging**
