### PR TITLE
Update SetPedRagdollOnCollision.md

### PR DESCRIPTION
**Pull request by Peter-Greek**
Updated Native Description

### CODE REVIEW

**Comment by AvarianKnight** [comment]
Please read the contribution guidelines on [descriptions](https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md#descriptions) the description should not be in code fences

**Review by stannum-cfx — CHANGES_REQUESTED** [review]
Please take the description out of the code block.

**Comment by 4mmonium** [comment]
Any update on this @Xerxes468893? Thanks!

**Comment by Peter-Greek** [comment]
Should be fixed now

**Pull request merged**
