### PR TITLE
Update SetEntityAsNoLongerNeeded.md

### PR DESCRIPTION
**Pull request by Tianshee**
Added important note.

### CODE REVIEW

**Comment by Tianshee** [comment]
You checked and didn't get same result or just biased and didn't read anything?

**Comment by Tianshee** [comment]
It's either a bug or lack of documentation. And FiveM geniuses that are always right are absolutely sure that it's not a bug. So documentation should be updated. Right? No, you declined that addition. Then it's not a bug, not lacking documentation. What then?

**Comment by Bluethefurry** [comment]
You removed the ```quotations```, also, the information is incorrect and/or useless, SetEntityAsNoLongerNeeded works without any special checks or prerequisites.

**Comment by blattersturm** [comment]
This is not the place for discussing drama. Locked.

If you wish to discuss this, do so on the forums, on Discord, or using email to support@fivem.net.

In addition, the documentation is _not_ the place for placing workarounds to perceived issues, perceived issues should be fixed using a pull request to the FiveM repository or reported as a well-written and objective report with a repro.

**Pull request closed without merging**
