### PR TITLE
feat(natives/2545): introduce new natives from the 2545 gamebuild

### PR DESCRIPTION
**Pull request by ahcenezdh**
For the enum eHudColours  i'm not sure, i found this enum on a git repo so please check first. For the native TASK_WARP_PED_DIRECTLY_INTO_COVER more work could be done to document how to get a coverIndex

### CODE REVIEW

**Review by PsychoShock — APPROVED** [review]
Hello,

I have personally reviewed the enum list and it semms to be all valid. Good job on this PR :)

Thanks

**Comment by ahcenezdh** [comment]
@AvarianKnight pinging you so you can see this PR

**Comment by ahcenezdh** [comment]
Hey, @AvarianKnight needs validation for what?

**Comment by AvarianKnight** [comment]
I need to double check stuff here, I'm abusing some of our flags right now instead of creating new ones.

**Pull request merged**
