### PR TITLE
update with cs_type annotation

### PR DESCRIPTION
**Pull request by gottfriedleibniz**
`diff NativesFive.cs.old NativesFive.cs.new` > https://pastebin.com/raw/ZgZTZwm5

### CODE REVIEW

**Comment by gottfriedleibniz** [comment]
One thing exposed by the diff: `0x76BBA2CEE66D47E9` conflicts with https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetPedEyeColor.md .

**Comment by Disquse** [comment]
> 
> 
> One thing exposed by the diff: `0x76BBA2CEE66D47E9` conflicts with https://github.com/citizenfx/fivem/blob/master/ext/native-decls/GetPedEyeColor.md .
> 
> Both natives also return the same value: `CPedHeadBlendData + 0x136` (0x140689551).

Yeah, I implemented this native when the original eye color getter wasn't found :(

**Comment by blattersturm** [comment]
> unless someone calls CFX native directly.

... and the all-too-common case of the 'old' native decl baseline in manifest-less __resource, maybe.

**Comment by blattersturm** [comment]
As to the CI build:

> Failed to build docs: AUDIO/IsMissionNewsStoryUnlocked.md AUDIO/N_0xbf4dc1784be94dfa.md AUDIO/OverrideMicrophoneSettings.md AUDIO/OverridePlayerGroundMaterial.md AUDIO/SetAmbientVoiceNameHash.md AUDIO/SetAmbientZoneState.md AUDIO/SetScriptUpdateDoorAudio.md AUDIO/SetSirenWithNoDriver.md CAM/ClampGameplayCamYaw.md ENTITY/RemoveModelHide.md GRAPHICS/FadeDecalsInRange.md HUD/DisplayRadar.md HUD/EndTextCommandOverrideButtonText.md MISC/GetProjectileNearPed.md MISC/IsProjectileTypeInAngledArea.md MISC/QueueMissionRepeatLoad.md MISC/SetFireAmmoThisFrame.md MONEY/NetworkPayMatchEntryFee.md MONEY/NetworkSpentBetting.md NETSHOPPING/NetGameserverBasketIsFull.md NETSHOPPING/NetGameserverGetTransactionManagerData.md NETWORK/CloudGetAvailabilityCheckResult.md NETWORK/GetCommerceProductPrice.md NETWORK/GetMaxNumNetworkPeds.md NETWORK/N_0x74fb3e29e6d10fa9.md NETWORK/N_0xfae628f1e9adb239.md NETWORK/NetworkClanGetUiFormattedTag.md NETWORK/UgcGetContentPath.md NETWORK/UgcHasGetFinished.md PAD/GetControlInstructionalButton.md PATHFIND/GetNthClosestVehicleNodeFavourDirection.md PED/HasPedheadshotImgUploadFailed.md PED/IsPedheadshotImgUploadAvailable.md PED/N_0x9c6a6c19b6c0c496.md PHYSICS/LoadRopeData.md PLAYER/RemovePlayerHelmet.md VEHICLE/RollDownWindow.md VEHICLE/RollUpWindow.md VEHICLE/SetBoatSinksWhenWrecked.md VEHICLE/SetDisableVehicleFlightNozzlePosition.md VEHICLE/SetGarbageTrucks.md VEHICLE/SetHeliTailExplodeThrowDashboard.md VEHICLE/SetPickupRopeLengthForCargobob.md VEHICLE/SetPlayersLastVehicle.md VEHICLE/SetRandomBoats.md VEHICLE/SetVehicleExclusiveDriver.md VEHICLE/SetVehicleHandlingHashForAi.md VEHICLE/SetVehicleReduceTraction.md VEHICLE/SetVehicleWheelsCanBreak.md VEHICLE/SmashVehicleWindow.md VEHICLE/StartPlaybackRecordedVehicleUsingAi.md VEHICLE/StartVehicleAlarm.md VEHICLE/SwitchTrainTrack.md WEAPON/CreateAirDefenseArea.md WEAPON/CreateAirDefenseSphere.md WEAPON/GetMaxAmmoByType.md WEAPON/GetPedAmmoByType.md WEAPON/GetPedWeaponLiveryColor.md WEAPON/GetWeaponDamage.md WEAPON/GetWeaponObjectLiveryColor.md WEAPON/GetWeaponTimeBetweenShots.md WEAPON/GiveLoadoutToPed.md WEAPON/N_0xa2c9ac24b4061285.md WEAPON/SetPedAmmoByType.md WEAPON/SetPedWeaponLiveryColor.md WEAPON/SetWeaponObjectLiveryColor.md

Why?

> .travis/run-pr: line 32:  8852 Segmentation fault      node "$BUILDER_ROOT/verify-one.js" "$entry"

Helpful.

**Comment by blattersturm** [comment]
> Both natives also return the same value

... therefore I _suspect_ even the table-hashing 'random' ordering thing won't lead to inconsistent results.

**Pull request merged**
