### PR TITLE
Update SetPedStrafeClipset.md

### PR DESCRIPTION
**Pull request by Tianshee**
Defines movement when _aiming_.

### CODE REVIEW

**Comment by Tianshee** [comment]
Like this?

**Comment by Tianshee** [comment]
Or ``` must be removed everywhere?

**Comment by Tianshee** [comment]
Or maybe like this...

**Comment by smallo92** [comment]
You had it right the second commit. The 3rd one is wrong, and you could have easily seen that by looking at any other previously accepted PRs.

**Comment by Tianshee** [comment]
Some accepted commits have even multiple ``` blocks.

**Pull request closed without merging**
