### PR TITLE
Update DetachEntity.md

### PR DESCRIPTION
**Pull request by ThexProdige**
p2 is not collision, but I do not know what it is

### CODE REVIEW

**Comment by technetium-cfx** [comment]
Good testing. Before I merge, how are you certain `p2` is not `collision`?

**Comment by technetium-cfx** [comment]
Any update @ThexProdige?

**Comment by ThexProdige** [comment]
Hello ! no for the moment ! :)
Sur 13/11/2020 00:06:10, Technetium <notifications@github.com> a écrit:
Any update @ThexProdige [https://github.com/ThexProdige]?

**Comment by technetium-cfx** [comment]
Okay, keeping the collision naming for now until further research.

**Pull request merged**
