### PR TITLE
Added Benny + Bespoke wheels

### PR DESCRIPTION
**Pull request by cqmpact**
Added 2 new wheel types.

### CODE REVIEW

**Comment by technetium-cfx** [comment]
Why'd you close you first PR? 😛

**Comment by cqmpact** [comment]
> 
> 
> Why'd you close your first PR? 😛

I believe I had it in wrong order 😄

**Comment by technetium-cfx** [comment]
You can edit/amend existing PRs 😉

**Comment by cqmpact** [comment]
> 
> 
> You can edit/amend existing PRs 😉

Ah, now I know for the future.
Thank you 😄

**Pull request merged**
