### PR TITLE
Update CreateMissionTrain.md

### PR DESCRIPTION
**Pull request by Rytrak**
Addition of different parameters for the native, more advanced documentation
The different types of variations were tested in game

### CODE REVIEW

**Review by 4mmonium — CHANGES_REQUESTED** [review]
Hey there, some changes needed. I attached a file showing you how this PR should look. You can replace this PR with the contents from that file and resubmit if you want.

Thanks!

[CreateMissionTrain.md](https://github.com/citizenfx/natives/files/11835146/CreateMissionTrain.md)

**Comment by Rytrak** [comment]
Hey, I've just sent the modification to a new commit

**Comment by 4mmonium** [comment]
> Hey, I've just sent the modification to a new commit

I will approve this now, thank you!

**Review by 4mmonium — APPROVED** [review]

**Comment by gottfriedleibniz** [comment]
It'd probably be best to update the `Train Models and variation id:` section. If I recall correctly, b2372 added additional train configurations so the section as is will be only be true for `>= b2372` or `< b2372`. My "trains.xml" comment was an incredibly lazy attempt at referencing that.

Also, should double check if removing `freight` is correct.

**Comment by 4mmonium** [comment]
> It'd probably be best to update the `Train Models and variation id:` section. If I recall correctly, b2372 added additional train configurations so the section as is will be only be true for `>= b2372` or `< b2372`. My "trains.xml" comment was an incredibly lazy attempt at referencing that.
> 
> Also, should double check if removing `freight` is correct.

I will take a look at an updated `trains.xml` soon, thank you for your feedback! 🙂

**Comment by 4mmonium** [comment]
Ok, I compared between a very old build of the game (1.0.323.1) by downloading from steam's depot downloader, and the current build, and it looks like these freight configurations were added (as you were saying).

```xml
<train_config
			name = "freight_config24"
			populate_train_dist = "40.0"
			announce_stations = "false"
			doors_beep = "false"
			carriages_hang = "false"
			carriages_swing = "false"
			link_tracks_with_adjacent_stations = "true"
			carriage_gap = "0.1"
			no_random_spawn = "true">
			
			<carriage
					model_name = "freight"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "1.65"
			repeat_count = "1" />
			
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "4" />	
			
			<carriage
				model_name = "freightgrain"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.99"
			repeat_count = "1" />
			
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "1" />	
	</train_config>

	<train_config
			name = "freight_config25"
			populate_train_dist = "40.0"
			announce_stations = "false"
			doors_beep = "false"
			carriages_hang = "false"
			carriages_swing = "false"
			link_tracks_with_adjacent_stations = "true"
			carriage_gap = "0.1"
			no_random_spawn = "true">

			<carriage
					model_name = "freight"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "1.65"
			repeat_count = "1" />
			<carriage
					model_name = "freightgrain"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />			
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "1" />
			<carriage
					model_name = "tankercar"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
					model_name = "freightgrain"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
					model_name = "tankercar"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "1" />
			<carriage
					model_name = "freightgrain"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "1" />
			<carriage
					model_name = "tankercar"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "2" />
			<carriage
					model_name = "freightcar2"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.70"
			repeat_count = "1" />			
			<carriage
					model_name = "tankercar"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
				model_name = "freightcar2"
				max_peds_per_carriage = "0"
				flip_model_dir = "false"
				do_interior_lights = "true"
				carriage_vert_offset = "0.70"
			repeat_count = "1" />
			<carriage
					model_name = "freightgrain"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "1" />
			<carriage
					model_name = "tankercar"
					max_peds_per_carriage = "0"
					flip_model_dir = "false"
					do_interior_lights = "true"
					carriage_vert_offset = "0.99"
			repeat_count = "2" />
	</train_config>
``` 

Also added to `freight_group` configs.

```xml
<train_config_ref name = "freight_config24" />	
<train_config_ref name = "freight_config25" />
```

I will be testing this and then most likely request changes, since there's more that could be added to this.
Thank you for your feedback once again!

**Comment by Rytrak** [comment]
24 and 25 are new train variations?

**Comment by 4mmonium** [comment]
> 24 and 25 are new train variations?

The metro variation id got switched from 24 to 25 since build 2372. I did more research anyway and will explain what my proposed changes are soon.

**Review by 4mmonium — CHANGES_REQUESTED** [review]
Ok, I have went through the native, including train configurations, also comparing with older builds of the game and it turns out that there have been a couple changes since 2372.

Starting from the native, two new arguments were added which I documented:

```
NativeDB Added Parameter 6: BOOL isNetwork
NativeDB Added Parameter 7: BOOL netMissionEntity
```

I verified this by looking at the `CREATE_VEHICLE` native that also calls matching methods for this.

Metro variation id has changed from 24 to 25 since build 2372.

I left my documentation attached. I also provided a basic `Lua` example.
[CreateMissionTrain.md](https://github.com/citizenfx/natives/files/11876126/CreateMissionTrain.md)

**Comment by Rytrak** [comment]
I update my PR to add your documentation?

**Comment by 4mmonium** [comment]
> I update my PR to add your documentation?

Correct, thank you! 🙂

**Comment by Rytrak** [comment]
ok it's good ;)

**Pull request merged**
