### PR TITLE
Modified SetVehicleLivery

### PR DESCRIPTION
**Pull request by Yimura**
Modified SetVehicleLivery to notify that it doesn't work and instead you should use SetVehicleMod

### CODE REVIEW

**Comment by Frosty-Ice** [comment]
That's not true at all. There's vehicles such as the Windsor that use this native to set their livery.

**Comment by Yimura** [comment]
Oh is it, I did use 1 small sample size of vehicles when applying Liveries to vehicles (10 or so) and had instant results with SetVehicleMod. Are there any other vehicles that work with SetVehicleLivery, do these work with SetVehicleMod?

**Comment by Frosty-Ice** [comment]
The Sanchez is another. You can use GetVehicleLiveryCount to see if the vehicle has settable liveries via this method.

**Comment by Yimura** [comment]
You appear to be correct, I tested it in-game and the Windsor does not use SetVehicleMod and GetNumVehMod does not work either for modIndex 48.

**Comment by Yimura** [comment]
I've modified the markdown file accordingly to differentiate between vehicles that use `GetVehicleLiveryCount(veh)` and `GetNumVehicleMods(veh, 48)`

**Comment by technetium-cfx** [comment]
I don't know, this makes very little sense to me.

**Pull request closed without merging**
